version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15.1-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=django_dev
  sqs:
    image: roribio16/alpine-sqs
  web:
    container_name: web
    build: .
    command: tail -f /dev/null
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - ./.env.dev
    depends_on:
      - sqs
      - db
  nginx:	
    build: ./nginx	
    ports:	
      - 80:80	
    volumes:	
      - static_files:/app/staticfiles	
    depends_on:	
      - web	
  celery:
    build: .
    command: celery -A starter worker -l info
    volumes:
      - ./:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - sqs
  beat:
    build: .
    command: celery -A starter beat -l info
    volumes:
      - ./:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - sqs


volumes:
  postgres_data:
  static_files:	